using System.Collections;
using UnityEngine;
using TMPro;
using UnityEngine.UI;

/// <summary>
/// Interfaz de Usuario (HUD en Realidad Virtual) para mostrar los Puntos, la Vida del jugador y los Power-Ups activos.
/// Permanece cómodamente visible en el campo de visión del jugador con auto-generación de interfaz.
/// </summary>
public class PlayerHUD : MonoBehaviour
{
    public static PlayerHUD Instance { get; private set; }

    [Header("Referencias de Texto UI")]
    [Tooltip("Texto para mostrar la puntuación")]
    public TextMeshProUGUI scoreText;

    [Tooltip("Texto para mostrar la vida / corazones")]
    public TextMeshProUGUI healthText;

    [Tooltip("Texto para mostrar el estado de los Power-Ups activos")]
    public TextMeshProUGUI powerUpStatusText;

    [Header("Configuración de Posición en VR")]
    [Tooltip("Distancia desde la cámara")]
    public float distanceFromCamera = 1.35f;

    [Tooltip("Desplazamiento horizontal y vertical respecto al centro de visión")]
    public Vector3 offset = new Vector3(0f, 0.42f, 0f);

    [Tooltip("Velocidad de seguimiento suave del HUD")]
    public float followSpeed = 9.0f;

    [Header("Puntuación Global")]
    public static int totalScore = 0;

    private Camera targetCamera;
    private int displayedScore = 0;
    private Coroutine scoreAnimCoroutine;
    private Coroutine notificationCoroutine;

    void Awake()
    {
        Instance = this;
        targetCamera = Camera.main;
        if (targetCamera == null)
        {
            var mover = Object.FindAnyObjectByType<VRAutoForwardMover>();
            if (mover != null) targetCamera = mover.GetComponentInChildren<Camera>();
        }

        if (scoreText == null || healthText == null || powerUpStatusText == null)
        {
            CrearHUDUIAutomatico();
        }
    }

    void OnDestroy()
    {
        if (Instance == this)
        {
            Instance = null;
        }
    }

    void Start()
    {
        if (targetCamera == null)
        {
            targetCamera = Camera.main;
        }

        displayedScore = totalScore;
        UpdateScoreDisplay(totalScore);

        PlayerHealth playerHealth = Object.FindAnyObjectByType<PlayerHealth>();
        if (playerHealth != null)
        {
            UpdateHealth(playerHealth.currentHealth, playerHealth.maxHealth);
        }
        else
        {
            UpdateHealth(3, 3);
        }

        ActualizarEstadoPowerUps();
    }

    void Update()
    {
        ActualizarEstadoPowerUps();
    }

    void LateUpdate()
    {
        if (targetCamera == null)
        {
            targetCamera = Camera.main;
            if (targetCamera == null) return;
        }

        // Posicionar el HUD frente a la cámara suavemente
        Vector3 targetPosition = targetCamera.transform.position 
            + (targetCamera.transform.forward * distanceFromCamera) 
            + (targetCamera.transform.up * offset.y) 
            + (targetCamera.transform.right * offset.x);

        transform.position = Vector3.Lerp(transform.position, targetPosition, Time.deltaTime * followSpeed);
        
        // Orientar hacia el jugador
        transform.rotation = Quaternion.LookRotation(transform.position - targetCamera.transform.position);
    }

    /// <summary>
    /// Suma puntos a la puntuación global y actualiza la interfaz.
    /// </summary>
    public static void AddScore(int points)
    {
        totalScore += points;
        Debug.Log($"[PlayerHUD] 🎯 +{points} PUNTOS | Puntuación total: {totalScore}");

        if (Instance == null)
        {
            GameObject hudObj = new GameObject("PlayerHUD_AutoGenerated");
            Instance = hudObj.AddComponent<PlayerHUD>();
        }
        
        Instance.OnScoreChanged(totalScore, points);
    }

    /// <summary>
    /// Reinicia la puntuación al iniciar una nueva partida o morir.
    /// </summary>
    public static void ResetScore()
    {
        totalScore = 0;
        if (Instance != null)
        {
            Instance.displayedScore = 0;
            Instance.UpdateScoreDisplay(0);
        }
    }

    private void OnScoreChanged(int newScore, int addedPoints)
    {
        if (scoreAnimCoroutine != null)
        {
            StopCoroutine(scoreAnimCoroutine);
        }
        scoreAnimCoroutine = StartCoroutine(AnimateScoreRoutine(newScore));
    }

    private IEnumerator AnimateScoreRoutine(int targetScore)
    {
        int startScore = displayedScore;
        float elapsed = 0f;
        float duration = 0.35f;

        // Efecto de pulso en el texto
        if (scoreText != null)
        {
            scoreText.transform.localScale = Vector3.one * 1.25f;
            scoreText.color = new Color(1.0f, 0.95f, 0.3f); // Amarillo brillante
        }

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / duration;
            displayedScore = (int)Mathf.Lerp(startScore, targetScore, t);
            UpdateScoreDisplay(displayedScore);
            yield return null;
        }

        displayedScore = targetScore;
        UpdateScoreDisplay(displayedScore);

        if (scoreText != null)
        {
            scoreText.transform.localScale = Vector3.one;
            scoreText.color = Color.white;
        }
    }

    public void UpdateScoreDisplay(int score)
    {
        if (scoreText != null)
        {
            scoreText.text = $"🎯 PUNTOS: <color=#FFD700>{score:N0}</color>";
        }
    }

    /// <summary>
    /// Actualiza la visualización de la vida (corazones y número).
    /// </summary>
    public void UpdateHealth(int currentHealth, int maxHealth)
    {
        if (healthText != null)
        {
            string hearts = "";
            for (int i = 0; i < maxHealth; i++)
            {
                if (i < currentHealth)
                {
                    hearts += "<color=#FF3B30>❤️</color> ";
                }
                else
                {
                    hearts += "<color=#555555>🖤</color> ";
                }
            }

            healthText.text = $"VIDA: {hearts}({currentHealth}/{maxHealth})";
        }
    }

    public void ActualizarEstadoPowerUps()
    {
        if (powerUpStatusText == null) return;
        if (PowerUpManager.Instance == null)
        {
            powerUpStatusText.text = "";
            return;
        }

        string status = "";

        if (PowerUpManager.Instance.HasShield)
        {
            status += "<color=#00E5FF>🛡️ ESCUDO ACTIVO</color>  ";
        }

        if (PowerUpManager.Instance.IsSlowMotionActive)
        {
            status += $"<color=#D580FF>⏱️ LENTO: {PowerUpManager.Instance.SlowMotionTimeRemaining:F1}s</color>  ";
        }

        if (PowerUpManager.Instance.IsDoubleScoreActive)
        {
            status += $"<color=#FFD700>⭐ 2X PUNTOS: {PowerUpManager.Instance.DoubleScoreTimeRemaining:F1}s</color>  ";
        }

        powerUpStatusText.text = status;
    }

    public void MostrarNotificacionPowerUp(PowerUpDataSO data)
    {
        if (notificationCoroutine != null) StopCoroutine(notificationCoroutine);
        notificationCoroutine = StartCoroutine(NotificacionPowerUpRutina(data));
    }

    private IEnumerator NotificacionPowerUpRutina(PowerUpDataSO data)
    {
        if (powerUpStatusText != null && data != null)
        {
            powerUpStatusText.text = $"<size=120%>{data.iconEmoji} ¡{data.powerUpName.ToUpper()} ACTIVADO!</size>";
            yield return new WaitForSeconds(1.5f);
        }
        ActualizarEstadoPowerUps();
    }

    private void CrearHUDUIAutomatico()
    {
        Canvas canvas = GetComponent<Canvas>();
        if (canvas == null)
        {
            canvas = gameObject.AddComponent<Canvas>();
        }
        canvas.renderMode = RenderMode.WorldSpace;
        canvas.worldCamera = targetCamera;

        CanvasScaler scaler = GetComponent<CanvasScaler>();
        if (scaler == null)
        {
            scaler = gameObject.AddComponent<CanvasScaler>();
            scaler.dynamicPixelsPerUnit = 3f;
        }

        RectTransform rt = GetComponent<RectTransform>();
        if (rt != null)
        {
            rt.sizeDelta = new Vector2(760f, 180f);
            transform.localScale = Vector3.one * 0.0016f;
        }

        // Panel contenedor estilizado
        GameObject panelObj = new GameObject("HUD_Panel");
        panelObj.transform.SetParent(transform, false);
        RectTransform panelRT = panelObj.AddComponent<RectTransform>();
        panelRT.anchorMin = Vector2.zero;
        panelRT.anchorMax = Vector2.one;
        panelRT.sizeDelta = Vector2.zero;

        Image panelImg = panelObj.AddComponent<Image>();
        panelImg.color = new Color(0.06f, 0.06f, 0.06f, 0.88f);

        Outline outline = panelObj.AddComponent<Outline>();
        outline.effectColor = new Color(0.9f, 0.75f, 0.2f, 0.8f);
        outline.effectDistance = new Vector2(2.5f, -2.5f);

        // Texto de Puntos (Arriba Izquierda)
        GameObject scoreObj = new GameObject("Score_Text");
        scoreObj.transform.SetParent(panelObj.transform, false);
        RectTransform scoreRT = scoreObj.AddComponent<RectTransform>();
        scoreRT.anchorMin = new Vector2(0.04f, 0.45f);
        scoreRT.anchorMax = new Vector2(0.50f, 0.95f);
        scoreRT.sizeDelta = Vector2.zero;

        scoreText = scoreObj.AddComponent<TextMeshProUGUI>();
        scoreText.text = $"🎯 PUNTOS: <color=#FFD700>{totalScore:N0}</color>";
        scoreText.fontSize = 32;
        scoreText.fontStyle = FontStyles.Bold;
        scoreText.alignment = TextAlignmentOptions.MidlineLeft;
        scoreText.color = Color.white;

        // Texto de Vida (Arriba Derecha)
        GameObject healthObj = new GameObject("Health_Text");
        healthObj.transform.SetParent(panelObj.transform, false);
        RectTransform healthRT = healthObj.AddComponent<RectTransform>();
        healthRT.anchorMin = new Vector2(0.50f, 0.45f);
        healthRT.anchorMax = new Vector2(0.96f, 0.95f);
        healthRT.sizeDelta = Vector2.zero;

        healthText = healthObj.AddComponent<TextMeshProUGUI>();
        healthText.text = "VIDA: <color=#FF3B30>❤️</color> <color=#FF3B30>❤️</color> <color=#FF3B30>❤️</color> (3/3)";
        healthText.fontSize = 26;
        healthText.fontStyle = FontStyles.Bold;
        healthText.alignment = TextAlignmentOptions.MidlineRight;
        healthText.color = Color.white;

        // Texto de Power-Ups Activos (Abajo Centrado)
        GameObject powerUpObj = new GameObject("PowerUp_Status_Text");
        powerUpObj.transform.SetParent(panelObj.transform, false);
        RectTransform powerUpRT = powerUpObj.AddComponent<RectTransform>();
        powerUpRT.anchorMin = new Vector2(0.04f, 0.05f);
        powerUpRT.anchorMax = new Vector2(0.96f, 0.45f);
        powerUpRT.sizeDelta = Vector2.zero;

        powerUpStatusText = powerUpObj.AddComponent<TextMeshProUGUI>();
        powerUpStatusText.text = "";
        powerUpStatusText.fontSize = 24;
        powerUpStatusText.fontStyle = FontStyles.Bold;
        powerUpStatusText.alignment = TextAlignmentOptions.Center;
        powerUpStatusText.color = new Color(0.3f, 0.9f, 1.0f);
    }
}
